/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ImshabyWidget {
        "expanded": boolean;
        "parishId": string;
    }
}
declare global {
    interface HTMLImshabyWidgetElement extends Components.ImshabyWidget, HTMLStencilElement {
    }
    var HTMLImshabyWidgetElement: {
        prototype: HTMLImshabyWidgetElement;
        new (): HTMLImshabyWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "imshaby-widget": HTMLImshabyWidgetElement;
    }
}
declare namespace LocalJSX {
    interface ImshabyWidget {
        "expanded"?: boolean;
        "parishId"?: string;
    }
    interface IntrinsicElements {
        "imshaby-widget": ImshabyWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "imshaby-widget": LocalJSX.ImshabyWidget & JSXBase.HTMLAttributes<HTMLImshabyWidgetElement>;
        }
    }
}
